spring:
  application:
    name: grpc-service

server:
  port: 8080

grpc:
  server:
    port: 9090
  client:
    ewallet-service:
      address: static://localhost:9091
      negotiation-type: plaintext
